### ISSUE TITLE
Create intro logos for each school

### ISSUE THREAD

**Issue by landalex** [Coffeeboys/RenewPass#18]
The notifications branch has a change to the intro activity, where selecting your school is done by tapping on your school's logo rather than selecting from a spinner.

Add the logos for all supported schools to the notification branch.
Schools supported:
1. SFU
2. UBC
3. BCIT
4. Cap U
5. Langara
6. VCC
7. NVIT
8. Douglas
9. Kwantlen
10. Emily Carr

**Comment by prayansh** [comment]
Will start working on that

**Comment by landalex** [comment]
Added with f395b30fb07cd4b2fa850e3e7c8ff1d82a86d972
