### ISSUE TITLE
Auto Renew

### ISSUE THREAD

**Issue by landalex** [Coffeeboys/RenewPass#2]
Set UPass to automatically renew.

Renewal can be done:
1. On a set day of the month
2. When the next month is available (either by checking to see if its available, or using Translink's sms notification)

**Comment by prayansh** [comment]
I am working on a feature that enables the user to setup a reminder in the app for each month. The notification then enables the user to update his UPass via the app.

**Comment by landalex** [comment]
Check out the notifications branch, we've done a little bit of work to get this started that you can build off of.

**Comment by prayansh** [comment]
Will do that
